spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/orders
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/changelog-master.yaml


server:
  port: 8080
