spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5433}/auth
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  liquibase:
    change-log: db/changelog/changelog-master.yaml


server:
  port: 8081
